[src.main]
type = "verilog"
src-files = ["examples/pp-params.sv"]

[constraints]
force-module-defaults = ["top"]
override-inst-params = true
override-local-params = true
override-forced-params = true
allow-override-non-constant = true

[smt]
out-file = "test.smtlib2"
