[featuresynth]
list-features-command = "python3 examples/secure-cpu-isa.py list"
oracle-command = "python3 examples/secure-cpu-isa.py check"
init-tests-file = "examples/secure-cpu-isa-init-tests.rktd"
resume-tests-file = "examples/secure-cpu-isa-resume-tests.rktd"
max-groups = 5
max-dependencies = 3
out-file = "out.fm.json"
